---
title: "Off-Lattice Cell-Based Monte Carlo Simulation"
author: "Elana J. Fertig, Thomas Sherman"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Off-Lattice Cell-Based Monte Carlo Simulation}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---
This vignette summarizes the uses and formats of the provided functions. Most of this information is available throughout the R documentation provided. This is an appendix which brings together all the provided information, to one place.

##Introduction

Off-Lattice Cell-Based Monte Carlo (OCMC) is a simulation based off previous data that enables the modeling of cell growth. The OCMC package is implemented in C++, and compiled and integrated into R using the Rcpp package. 

##Installation

source("http://www.bioconductor.org/biocLite.R")

biocLite("CellModel")

##Getting Started

In this section, we will describe the main function and its uses.

The following function, "runModel" will be the main and most basic function that will be run in the usage of this package. Below is the syntax of the function, only requiring two of its many parameters in order to create a model. An example of the proper syntax is provided below:
```{r}
# Runs the Model
runModel <- function(initialNum, runTime, density = 0.05,
                    meanGrowth = 0.15, varGrowth = 0.0, maxMigration = 0.5,
                    maxDeform = 0.075, maxRotate = 0.3, epsilon = 0.05,
                    delta = 5.0, outIncrement = 10, randSeed = 0)
runModel(10,10)
```

Each parameter will simulate a certain variable in cell growth:

* initialNum: the number of initial cells that will start in the model
* runTime: how long the model will run for
* density: the density the cells are seeded at
* meanGrowth: mean growth rate of cells
* varGrowth: the variance of the growth rate (assumed normal)
* maxMigration: farthest a cell can move in a single update
* maxDeform: most a cell can deform in a single update
* maxRotate: most a cell can rotate in a single update
* epsilon: model specific parameter
* delta: model specific parameter
* outIncrement: time increment to print status at
* randSeed: seed for the model

Upon running this function, a CellModel object will be created, along with the printing of the time, and interval specified by "runTime" and "outIncrement" respectively.
