#!/bin/bash

if [ "$1" != "" ]; then
    TOTAL_RUNS=$1
else
    TOTAL_RUNS=1
fi

DATE=`date +%Y%m%d_%H%M%S`
DIR=~/CancerInSilico/Output/$DATE/

mkdir -p $DIR
sbatch -D $DIR --array=1-$TOTAL_RUNS ~/CancerInSilico/inst/scripts/runCancerInSilico.sh $DATE
