// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// CellModel
Rcpp::NumericMatrix CellModel(SEXP init_num, SEXP run_time, SEXP density);
RcppExport SEXP CellModel_CellModel(SEXP init_numSEXP, SEXP run_timeSEXP, SEXP densitySEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type init_num(init_numSEXP);
    Rcpp::traits::input_parameter< SEXP >::type run_time(run_timeSEXP);
    Rcpp::traits::input_parameter< SEXP >::type density(densitySEXP);
    __result = Rcpp::wrap(CellModel(init_num, run_time, density));
    return __result;
END_RCPP
}
