// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// CellModel
Rcpp::NumericMatrix CellModel(int initialNum, int runTime);
RcppExport SEXP CellModel_CellModel(SEXP initialNumSEXP, SEXP runTimeSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type initialNum(initialNumSEXP);
    Rcpp::traits::input_parameter< int >::type runTime(runTimeSEXP);
    __result = Rcpp::wrap(CellModel(initialNum, runTime));
    return __result;
END_RCPP
}
