# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CellModel <- function(initialNum, runTime, density = 0.05, meanGrowth = 0.15, varGrowth = 0.0, apoptosisRate = 0.0, maxMigration = 0.5, maxDeform = 0.075, maxRotate = 0.3, epsilon = 0.05, delta = 5.0) {
    .Call('CellModel_CellModel', PACKAGE = 'CellModel', initialNum, runTime, density, meanGrowth, varGrowth, apoptosisRate, maxMigration, maxDeform, maxRotate, epsilon, delta)
}

