# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CellModel <- function(init_num, run_time, density) {
    .Call('CellModel_CellModel', PACKAGE = 'CellModel', init_num, run_time, density)
}

