# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CellModel <- function(initialNum, runTime, density, meanGrowth, varGrowth, maxMigration, maxDeform, maxRotate, epsilon, delta, outIncrement, randSeed, growthRates) {
    .Call('CellModel_CellModel', PACKAGE = 'CellModel', initialNum, runTime, density, meanGrowth, varGrowth, maxMigration, maxDeform, maxRotate, epsilon, delta, outIncrement, randSeed, growthRates)
}

